package com.algaworks.vinhos.model;



import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.validator.constraints.NotBlank;

/**
* Actor generated by hbm2java
*/

@Entity
public class Actor  {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
  private Short actorId;
	
	@NotBlank
  private String firstName;
	@NotBlank
  private String lastName;
  
  private Date lastUpdate;

 public Actor() {
 }

 public Actor(String firstName, String lastName, Date lastUpdate) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.lastUpdate = lastUpdate;
 }

 public Short getActorId() {
     return this.actorId;
 }
 
 public void setActorId(Short actorId) {
     this.actorId = actorId;
 }
 public String getFirstName() {
     return this.firstName;
 }
 
 public void setFirstName(String firstName) {
     this.firstName = firstName;
 }
 public String getLastName() {
     return this.lastName;
 }
 
 public void setLastName(String lastName) {
     this.lastName = lastName;
 }
 public Date getLastUpdate() {
     return this.lastUpdate;
 }
 
 public void setLastUpdate(Date lastUpdate) {
     this.lastUpdate = lastUpdate;
 }

@Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((actorId == null) ? 0 : actorId.hashCode());
	return result;
}

@Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	Actor other = (Actor) obj;
	if (actorId == null) {
		if (other.actorId != null)
			return false;
	} else if (!actorId.equals(other.actorId))
		return false;
	return true;
}




}


